workflows:
  android-twa-workflow:
    name: Android TWA Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Web App
        script: npm run build
      - name: Install Bubblewrap CLI
        script: npm install -g @bubblewrap/cli
      - name: Build Android Package
        script: |
          # Build jarayoni
          bubblewrap build --no-interactive
          # Qaysi fayllar yaratilganini tekshirish (Debug)
          ls -R
    artifacts:
      - "*.apk"
      - "*.aab"
      - "app-release.apk"
      - "app-release-bundle.aab"
    publishing:
      email:
        recipients:
          - azizbekbakirov39@gmail.com
